# Generated by Django 5.2.2 on 2025-06-08 10:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Home page"},
        ),
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("row", 0)],
                blank=True,
                block_lookup={0: ("wagtail.blocks.StructBlock", [[]], {})},
                null=True,
            ),
        ),
    ]
