# Generated by Django 5.2.2 on 2025-06-08 11:04

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_homepage_options_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("row", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "choices": [],
                            "default": "1/12",
                            "label": "Column size",
                            "required": False,
                        },
                    ),
                    1: ("wagtail.blocks.StructBlock", [[]], {}),
                    2: (
                        "wagtail.blocks.StreamBlock",
                        [[("tile", 1), ("card", 1)]],
                        {"blank": True, "label": "Block", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("column_size", 0), ("content", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("content", 3)]], {}),
                },
                null=True,
            ),
        ),
    ]
