# Generated by Django 5.2.2 on 2025-06-08 12:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("row", 6)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Headline", "max_length": 200, "required": False},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "required": False},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 0), ("body", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Bootstrap icon name",
                            "label": "Icon name",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 3), ("headline", 0), ("body", 1)]],
                        {},
                    ),
                    5: ("wagtail.blocks.StreamBlock", [[("tile", 2), ("card", 4)]], {}),
                    6: ("wagtail.blocks.StructBlock", [[("columns", 5)]], {}),
                },
                null=True,
            ),
        ),
    ]
