# Generated by Django 5.2.2 on 2025-06-08 13:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("row", 8)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Automatic size"),
                                ("12", "Full row"),
                                ("6", "Half - 1/2 column"),
                                ("4", "Thirds - 1/3 column"),
                                ("8", "Thirds - 2/3 column"),
                                ("3", "Quarters - 1/4 column"),
                                ("9", "Quarters - 3/4 column"),
                                ("2", "Sixths - 1/6 column"),
                                ("10", "Sixths - 5/6 column"),
                                ("1", "Twelfths - 1/12 column"),
                                ("5", "Twelfths - 5/12 column"),
                                ("7", "Twelfths - 7/12 column"),
                                ("11", "Twelfths - 11/12 column"),
                            ],
                            "label": "Column size",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Bootstrap-icon name",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("icon_name", 1)]], {}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Headline", "max_length": 200, "required": False},
                    ),
                    4: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 0),
                                ("icon", 2),
                                ("headline", 3),
                                ("body", 4),
                            ]
                        ],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("column_size", 0), ("headline", 3), ("body", 4)]],
                        {},
                    ),
                    7: ("wagtail.blocks.StreamBlock", [[("card", 5), ("tile", 6)]], {}),
                    8: ("wagtail.blocks.StreamBlock", [[("items", 7)]], {}),
                },
                null=True,
            ),
        ),
    ]
