# Generated by Django 5.2.2 on 2025-06-08 13:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("row", 0)],
                blank=True,
                block_lookup={0: ("wagtail.blocks.StructBlock", [[]], {})},
                null=True,
            ),
        ),
    ]
