# Generated by Django 5.2.2 on 2025-06-09 10:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0041_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("row", 10)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Automatic size"),
                                ("12", "Full row"),
                                ("6", "Half - 1/2 column"),
                                ("4", "Thirds - 1/3 column"),
                                ("8", "Thirds - 2/3 column"),
                                ("3", "Quarters - 1/4 column"),
                                ("9", "Quarters - 3/4 column"),
                                ("2", "Sixths - 1/6 column"),
                                ("10", "Sixths - 5/6 column"),
                                ("1", "Twelfths - 1/12 column"),
                                ("5", "Twelfths - 5/12 column"),
                                ("7", "Twelfths - 7/12 column"),
                                ("11", "Twelfths - 11/12 column"),
                            ],
                            "label": "Column size",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Always expanded"),
                                (
                                    "sm",
                                    "sm - Expand on small screens (phone, 576px) and larger",
                                ),
                                (
                                    "md",
                                    "md - Expand on medium screens (tablet, 768px) and larger",
                                ),
                                (
                                    "lg",
                                    "lg - Expand on large screens (laptop, 992px) and larger",
                                ),
                                (
                                    "xl",
                                    "xl - Expand on extra large screens (wide monitor, 1200px)",
                                ),
                            ],
                            "label": "Column breakpoint",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Headline", "max_length": 200, "required": False},
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 0),
                                ("column_breakpoint", 1),
                                ("headline", 2),
                                ("body", 3),
                            ]
                        ],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Bootstrap-icon name",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    6: ("wagtail.blocks.StructBlock", [[("icon_name", 5)]], {}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 0),
                                ("column_breakpoint", 1),
                                ("icon", 6),
                                ("headline", 2),
                                ("body", 3),
                            ]
                        ],
                        {},
                    ),
                    8: ("wagtail.blocks.StreamBlock", [[("tile", 4), ("card", 7)]], {}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 0),
                                ("column_breakpoint", 1),
                                ("columns", 8),
                            ]
                        ],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.StreamBlock",
                        [[("row", 9), ("tile", 4), ("card", 7)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
