# Generated by Django 5.2.2 on 2025-06-09 14:50

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0044_alter_homepage_body"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimplePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("text", 0), ("link", 7)],
                        blank=True,
                        block_lookup={
                            0: ("home.blocks.html.RichTextBlock", (), {}),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page link", "required": False},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave empty for document/page links to use their title.",
                                    "label": "Title",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"label": "Document link", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"label": "Download document", "required": False},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "External URL",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "label": "External URL open in new page",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("page_link", 1),
                                        ("title", 2),
                                        ("document_link", 3),
                                        ("document_download_flag", 4),
                                        ("external_link_url", 5),
                                        ("external_link_open_in_new_page_flag", 6),
                                    ]
                                ],
                                {},
                            ),
                        },
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
