# Generated by Django 5.2.4 on 2025-07-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0050_alter_homepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactsettings",
            name="city",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contactsettings",
            name="street",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contactsettings",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
