# Generated by Django 5.2.4 on 2025-07-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0051_contactsettings_city_contactsettings_street_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactsettings",
            name="email",
            field=models.EmailField(
                blank=True, max_length=200, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="contactsettings",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Phone number"
            ),
        ),
        migrations.AlterField(
            model_name="contactsettings",
            name="city",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="contactsettings",
            name="street",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Street"
            ),
        ),
        migrations.AlterField(
            model_name="contactsettings",
            name="zip_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Zip code"
            ),
        ),
    ]
