# Generated by Django 5.2.4 on 2025-07-12 11:34

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0052_contactsettings_email_contactsettings_phone_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Footer text"
                    ),
                ),
            ],
        ),
    ]
