# Generated by Django 5.2.4 on 2025-07-12 13:57

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0054_alter_footer_options_footer_expire_at_footer_expired_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpeningHoursSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opening_hours",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Opening hours"
                    ),
                ),
            ],
            options={
                "verbose_name": "Opening hours",
            },
        ),
    ]
