# Generated by Django 5.2.4 on 2025-07-12 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0057_flyerindexpage_flyerpage"),
        ("wagtaildocs", "0014_alter_document_file_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="flyerpage",
            name="flyer_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtaildocs.document",
            ),
        ),
    ]
