# Generated by Django 5.2.4 on 2025-07-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0058_flyerpage_flyer_document"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flyerpage",
            old_name="flyer_document",
            new_name="document",
        ),
        migrations.RenameField(
            model_name="flyerpage",
            old_name="teaser_image",
            new_name="image",
        ),
    ]
