# Generated by Django 5.2.4 on 2025-07-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0059_rename_flyer_document_flyerpage_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flyerpage",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Short description text",
                verbose_name="Description",
            ),
        ),
    ]
