# Generated by Django 5.2.4 on 2025-07-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0062_alter_footer_extra_slot_alter_homepage_body_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SimplePage",
        ),
    ]
