# Generated by Django 5.2.4 on 2025-07-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0064_contactsettings_main_menu_cta_document_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactsettings",
            name="main_menu_cta_text",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="MainMenu CTA link text",
            ),
        ),
    ]
