# Generated by Django 5.2.4 on 2025-07-26 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0066_alter_flyerpage_document_alter_flyerpage_image"),
        ("wagtaildocs", "0014_alter_document_file_size"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flyerpage",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtaildocs.document",
            ),
        ),
        migrations.AlterField(
            model_name="flyerpage",
            name="image",
            field=models.ForeignKey(
                help_text="Descriptive sample image (cropped to be rectangled).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
