# Generated by Django 5.2.4 on 2025-07-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0067_alter_flyerpage_document_alter_flyerpage_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flyerindexpage",
            options={"verbose_name": "Flyer index page"},
        ),
        migrations.AlterModelOptions(
            name="flyerpage",
            options={"verbose_name": "Flyer page"},
        ),
    ]
