# Generated by Django 5.2.4 on 2025-07-27 13:49

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0068_alter_flyerindexpage_options_alter_flyerpage_options"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("text", 0), ("heading", 3)],
                        blank=True,
                        block_lookup={
                            0: ("home.blocks.html.RichTextBlock", (), {}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Heading text", "required": True},
                            ),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "blank": True,
                                    "choices": [
                                        ("", "Select header level"),
                                        ("h1", "H1"),
                                        ("h2", "H2"),
                                        ("h3", "H3"),
                                        ("h4", "H4"),
                                    ],
                                },
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 1), ("level", 2)]],
                                {},
                            ),
                        },
                        verbose_name="Page body",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AlterField(
            model_name="footer",
            name="extra_slot",
            field=wagtail.fields.StreamField(
                [("text", 0), ("heading", 3), ("link", 10)],
                blank=True,
                block_lookup={
                    0: ("home.blocks.html.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading text", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select header level"),
                                ("h1", "H1"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("level", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page link", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave empty for document/page links to use their title.",
                            "label": "Title",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Open in new page", "required": False},
                    ),
                    7: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "Document link", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Download document", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "External URL", "max_length": 255, "required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page_link", 4),
                                ("title", 5),
                                ("open_in_new_page_flag", 6),
                                ("document_link", 7),
                                ("document_download_flag", 8),
                                ("external_link_url", 9),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
                verbose_name="Extra footer slot",
            ),
        ),
    ]
