# Generated by Django 5.2.4 on 2025-07-27 14:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0069_standardpage_alter_footer_extra_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footer",
            name="extra_slot",
            field=wagtail.fields.StreamField(
                [("text", 0), ("heading", 4), ("link", 11)],
                blank=True,
                block_lookup={
                    0: ("home.blocks.html.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Custom element id", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading text", "required": True},
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select header level"),
                                ("h1", "H1"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("custom_element_id", 1), ("text", 2), ("level", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page link", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave empty for document/page links to use their title.",
                            "label": "Title",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Open in new page", "required": False},
                    ),
                    8: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "Document link", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Download document", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "External URL", "max_length": 255, "required": False},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page_link", 5),
                                ("title", 6),
                                ("open_in_new_page_flag", 7),
                                ("document_link", 8),
                                ("document_download_flag", 9),
                                ("external_link_url", 10),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
                verbose_name="Extra footer slot",
            ),
        ),
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("text", 0), ("heading", 4)],
                blank=True,
                block_lookup={
                    0: ("home.blocks.html.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Custom element id", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading text", "required": True},
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select header level"),
                                ("h1", "H1"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("custom_element_id", 1), ("text", 2), ("level", 3)]],
                        {},
                    ),
                },
                verbose_name="Page body",
            ),
        ),
    ]
