# Generated by Django 5.2.5 on 2025-08-31 10:53

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0077_alter_footer_extra_slot_alter_homepage_body_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Carousel",
            },
        ),
        migrations.CreateModel(
            name="CarouselSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [("text", 0), ("heading", 5)],
                        blank=True,
                        block_lookup={
                            0: ("home.blocks.html.RichTextBlock", (), {}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Heading text", "required": True},
                            ),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "blank": True,
                                    "choices": [
                                        ("", "Select header level"),
                                        ("h1", "H1"),
                                        ("h2", "H2"),
                                        ("h3", "H3"),
                                        ("h4", "H4"),
                                    ],
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Custom element id", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("custom_element_id", 3)]],
                                {},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 1), ("level", 2), ("settings", 4)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "carousel",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carousel_slides",
                        to="home.carousel",
                        verbose_name="Carousel",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carousel slide",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
