# Generated by Django 5.2.5 on 2025-09-01 11:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0082_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("row", 22), ("flyer_swiper", 23), ("carousel", 25)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Automatic size"),
                                ("12", "Full row"),
                                ("6", "Half - 1/2 column"),
                                ("4", "Thirds - 1/3 column"),
                                ("8", "Thirds - 2/3 column"),
                                ("3", "Quarters - 1/4 column"),
                                ("9", "Quarters - 3/4 column"),
                                ("2", "Sixths - 1/6 column"),
                                ("10", "Sixths - 5/6 column"),
                                ("1", "Twelfths - 1/12 column"),
                                ("5", "Twelfths - 5/12 column"),
                                ("7", "Twelfths - 7/12 column"),
                                ("11", "Twelfths - 11/12 column"),
                            ],
                            "label": "Column size",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Always expanded"),
                                (
                                    "sm",
                                    "sm - Expand on small screens (phone, 576px) and larger",
                                ),
                                (
                                    "md",
                                    "md - Expand on medium screens (tablet, 768px) and larger",
                                ),
                                (
                                    "lg",
                                    "lg - Expand on large screens (laptop, 992px) and larger",
                                ),
                                (
                                    "xl",
                                    "xl - Expand on extra large screens (wide monitor, 1200px)",
                                ),
                            ],
                            "label": "Column breakpoint",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Headline", "max_length": 200, "required": False},
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "required": False},
                    ),
                    4: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page link", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave empty for document/page links to use their title.",
                            "label": "Title",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Open in new page", "required": False},
                    ),
                    7: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "Document link", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Download document", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "External URL", "max_length": 255, "required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page_link", 4),
                                ("title", 5),
                                ("open_in_new_page_flag", 6),
                                ("document_link", 7),
                                ("document_download_flag", 8),
                                ("external_link_url", 9),
                            ]
                        ],
                        {"label": "Link", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default theme"),
                                ("green", "Green theme"),
                            ],
                            "label": "Tile theme",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 0),
                                ("column_breakpoint", 1),
                                ("headline", 2),
                                ("body", 3),
                                ("link", 10),
                                ("theme", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("column_size", 0), ("column_breakpoint", 1), ("image", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Bootstrap-icon name",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Custom element id", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("custom_element_id", 16)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("icon_name", 15), ("settings", 17)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 0),
                                ("column_breakpoint", 1),
                                ("icon", 18),
                                ("headline", 2),
                                ("body", 3),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("tile", 12),
                                ("tile_image", 14),
                                ("card", 19),
                                ("card_image", 14),
                            ]
                        ],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 0),
                                ("column_breakpoint", 1),
                                ("columns", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("row", 21),
                                ("tile", 12),
                                ("tile_image", 14),
                                ("card", 19),
                                ("card_image", 14),
                            ]
                        ],
                        {},
                    ),
                    23: ("wagtail.blocks.StructBlock", [[("settings", 17)]], {}),
                    24: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.Carousel",),
                        {},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("carousel", 24), ("settings", 17)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
