# Generated by Django 5.2.5 on 2025-09-02 10:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0083_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footer",
            name="extra_slot",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("heading", 5),
                    ("link", 12),
                    ("row", 27),
                    ("flyer_swiper", 28),
                    ("carousel", 30),
                ],
                blank=True,
                block_lookup={
                    0: ("home.blocks.html.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading text", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select header level"),
                                ("h1", "H1"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Custom element id", "required": False},
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("custom_element_id", 3)]], {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("level", 2), ("settings", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page link", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave empty for document/page links to use their title.",
                            "label": "Title",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Open in new page", "required": False},
                    ),
                    9: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "Document link", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Download document", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "External URL", "max_length": 255, "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page_link", 6),
                                ("title", 7),
                                ("open_in_new_page_flag", 8),
                                ("document_link", 9),
                                ("document_download_flag", 10),
                                ("external_link_url", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Automatic size"),
                                ("12", "Full row"),
                                ("6", "Half - 1/2 column"),
                                ("4", "Thirds - 1/3 column"),
                                ("8", "Thirds - 2/3 column"),
                                ("3", "Quarters - 1/4 column"),
                                ("9", "Quarters - 3/4 column"),
                                ("2", "Sixths - 1/6 column"),
                                ("10", "Sixths - 5/6 column"),
                                ("1", "Twelfths - 1/12 column"),
                                ("5", "Twelfths - 5/12 column"),
                                ("7", "Twelfths - 7/12 column"),
                                ("11", "Twelfths - 11/12 column"),
                            ],
                            "label": "Column size",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Always expanded"),
                                (
                                    "sm",
                                    "sm - Expand on small screens (phone, 576px) and larger",
                                ),
                                (
                                    "md",
                                    "md - Expand on medium screens (tablet, 768px) and larger",
                                ),
                                (
                                    "lg",
                                    "lg - Expand on large screens (laptop, 992px) and larger",
                                ),
                                (
                                    "xl",
                                    "xl - Expand on extra large screens (wide monitor, 1200px)",
                                ),
                            ],
                            "label": "Column breakpoint",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Headline", "max_length": 200, "required": False},
                    ),
                    16: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "required": False},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page_link", 6),
                                ("title", 7),
                                ("open_in_new_page_flag", 8),
                                ("document_link", 9),
                                ("document_download_flag", 10),
                                ("external_link_url", 11),
                            ]
                        ],
                        {"label": "Link", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default theme"),
                                ("green", "Green theme"),
                            ],
                            "label": "Tile theme",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 13),
                                ("column_breakpoint", 14),
                                ("headline", 15),
                                ("body", 16),
                                ("link", 17),
                                ("theme", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 13),
                                ("column_breakpoint", 14),
                                ("image", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Bootstrap-icon name",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("icon_name", 22), ("settings", 4)]],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 13),
                                ("column_breakpoint", 14),
                                ("icon", 23),
                                ("headline", 15),
                                ("body", 16),
                            ]
                        ],
                        {},
                    ),
                    25: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("tile", 19),
                                ("tile_image", 21),
                                ("card", 24),
                                ("card_image", 21),
                            ]
                        ],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 13),
                                ("column_breakpoint", 14),
                                ("columns", 25),
                            ]
                        ],
                        {},
                    ),
                    27: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("row", 26),
                                ("tile", 19),
                                ("tile_image", 21),
                                ("card", 24),
                                ("card_image", 21),
                            ]
                        ],
                        {},
                    ),
                    28: ("wagtail.blocks.StructBlock", [[("settings", 4)]], {}),
                    29: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.Carousel",),
                        {},
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("carousel", 29), ("settings", 4)]],
                        {},
                    ),
                },
                null=True,
                verbose_name="Extra footer slot",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("row", 22), ("hero", 24)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Automatic size"),
                                ("12", "Full row"),
                                ("6", "Half - 1/2 column"),
                                ("4", "Thirds - 1/3 column"),
                                ("8", "Thirds - 2/3 column"),
                                ("3", "Quarters - 1/4 column"),
                                ("9", "Quarters - 3/4 column"),
                                ("2", "Sixths - 1/6 column"),
                                ("10", "Sixths - 5/6 column"),
                                ("1", "Twelfths - 1/12 column"),
                                ("5", "Twelfths - 5/12 column"),
                                ("7", "Twelfths - 7/12 column"),
                                ("11", "Twelfths - 11/12 column"),
                            ],
                            "label": "Column size",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Always expanded"),
                                (
                                    "sm",
                                    "sm - Expand on small screens (phone, 576px) and larger",
                                ),
                                (
                                    "md",
                                    "md - Expand on medium screens (tablet, 768px) and larger",
                                ),
                                (
                                    "lg",
                                    "lg - Expand on large screens (laptop, 992px) and larger",
                                ),
                                (
                                    "xl",
                                    "xl - Expand on extra large screens (wide monitor, 1200px)",
                                ),
                            ],
                            "label": "Column breakpoint",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Headline", "max_length": 200, "required": False},
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "required": False},
                    ),
                    4: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page link", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave empty for document/page links to use their title.",
                            "label": "Title",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Open in new page", "required": False},
                    ),
                    7: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "Document link", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Download document", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "External URL", "max_length": 255, "required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page_link", 4),
                                ("title", 5),
                                ("open_in_new_page_flag", 6),
                                ("document_link", 7),
                                ("document_download_flag", 8),
                                ("external_link_url", 9),
                            ]
                        ],
                        {"label": "Link", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default theme"),
                                ("green", "Green theme"),
                            ],
                            "label": "Tile theme",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 0),
                                ("column_breakpoint", 1),
                                ("headline", 2),
                                ("body", 3),
                                ("link", 10),
                                ("theme", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("column_size", 0), ("column_breakpoint", 1), ("image", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Bootstrap-icon name",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Custom element id", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("custom_element_id", 16)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("icon_name", 15), ("settings", 17)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 0),
                                ("column_breakpoint", 1),
                                ("icon", 18),
                                ("headline", 2),
                                ("body", 3),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("tile", 12),
                                ("tile_image", 14),
                                ("card", 19),
                                ("card_image", 14),
                            ]
                        ],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 0),
                                ("column_breakpoint", 1),
                                ("columns", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("row", 21),
                                ("tile", 12),
                                ("tile_image", 14),
                                ("card", 19),
                                ("card_image", 14),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hero background will be blurred by default",
                            "label": "Background image",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("background_image", 23), ("settings", 17)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("heading", 5),
                    ("link", 12),
                    ("row", 27),
                    ("flyer_swiper", 28),
                    ("carousel", 30),
                ],
                blank=True,
                block_lookup={
                    0: ("home.blocks.html.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading text", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select header level"),
                                ("h1", "H1"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Custom element id", "required": False},
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("custom_element_id", 3)]], {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("level", 2), ("settings", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page link", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave empty for document/page links to use their title.",
                            "label": "Title",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Open in new page", "required": False},
                    ),
                    9: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "Document link", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Download document", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "External URL", "max_length": 255, "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page_link", 6),
                                ("title", 7),
                                ("open_in_new_page_flag", 8),
                                ("document_link", 9),
                                ("document_download_flag", 10),
                                ("external_link_url", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Automatic size"),
                                ("12", "Full row"),
                                ("6", "Half - 1/2 column"),
                                ("4", "Thirds - 1/3 column"),
                                ("8", "Thirds - 2/3 column"),
                                ("3", "Quarters - 1/4 column"),
                                ("9", "Quarters - 3/4 column"),
                                ("2", "Sixths - 1/6 column"),
                                ("10", "Sixths - 5/6 column"),
                                ("1", "Twelfths - 1/12 column"),
                                ("5", "Twelfths - 5/12 column"),
                                ("7", "Twelfths - 7/12 column"),
                                ("11", "Twelfths - 11/12 column"),
                            ],
                            "label": "Column size",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Always expanded"),
                                (
                                    "sm",
                                    "sm - Expand on small screens (phone, 576px) and larger",
                                ),
                                (
                                    "md",
                                    "md - Expand on medium screens (tablet, 768px) and larger",
                                ),
                                (
                                    "lg",
                                    "lg - Expand on large screens (laptop, 992px) and larger",
                                ),
                                (
                                    "xl",
                                    "xl - Expand on extra large screens (wide monitor, 1200px)",
                                ),
                            ],
                            "label": "Column breakpoint",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Headline", "max_length": 200, "required": False},
                    ),
                    16: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "required": False},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page_link", 6),
                                ("title", 7),
                                ("open_in_new_page_flag", 8),
                                ("document_link", 9),
                                ("document_download_flag", 10),
                                ("external_link_url", 11),
                            ]
                        ],
                        {"label": "Link", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default theme"),
                                ("green", "Green theme"),
                            ],
                            "label": "Tile theme",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 13),
                                ("column_breakpoint", 14),
                                ("headline", 15),
                                ("body", 16),
                                ("link", 17),
                                ("theme", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 13),
                                ("column_breakpoint", 14),
                                ("image", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Bootstrap-icon name",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("icon_name", 22), ("settings", 4)]],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 13),
                                ("column_breakpoint", 14),
                                ("icon", 23),
                                ("headline", 15),
                                ("body", 16),
                            ]
                        ],
                        {},
                    ),
                    25: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("tile", 19),
                                ("tile_image", 21),
                                ("card", 24),
                                ("card_image", 21),
                            ]
                        ],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 13),
                                ("column_breakpoint", 14),
                                ("columns", 25),
                            ]
                        ],
                        {},
                    ),
                    27: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("row", 26),
                                ("tile", 19),
                                ("tile_image", 21),
                                ("card", 24),
                                ("card_image", 21),
                            ]
                        ],
                        {},
                    ),
                    28: ("wagtail.blocks.StructBlock", [[("settings", 4)]], {}),
                    29: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.Carousel",),
                        {},
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("carousel", 29), ("settings", 4)]],
                        {},
                    ),
                },
                verbose_name="Page body",
            ),
        ),
    ]
