# Generated by Django 5.2.5 on 2025-09-03 11:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0095_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("row", 35), ("hero", 38)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                            "help_text": "Gap between columns",
                            "label": "Spacing",
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Automatic size"),
                                ("12", "Full row"),
                                ("6", "Half - 1/2 column"),
                                ("4", "Thirds - 1/3 column"),
                                ("8", "Thirds - 2/3 column"),
                                ("3", "Quarters - 1/4 column"),
                                ("9", "Quarters - 3/4 column"),
                                ("2", "Sixths - 1/6 column"),
                                ("10", "Sixths - 5/6 column"),
                                ("1", "Twelfths - 1/12 column"),
                                ("5", "Twelfths - 5/12 column"),
                                ("7", "Twelfths - 7/12 column"),
                                ("11", "Twelfths - 11/12 column"),
                            ],
                            "label": "Column size",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Always expanded"),
                                (
                                    "sm",
                                    "sm - Expand on small screens (phone, 576px) and larger",
                                ),
                                (
                                    "md",
                                    "md - Expand on medium screens (tablet, 768px) and larger",
                                ),
                                (
                                    "lg",
                                    "lg - Expand on large screens (laptop, 992px) and larger",
                                ),
                                (
                                    "xl",
                                    "xl - Expand on extra large screens (wide monitor, 1200px)",
                                ),
                            ],
                            "label": "Column breakpoint",
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.StreamBlock", [[]], {}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Custom element id", "required": False},
                    ),
                    5: ("wagtail.blocks.StructBlock", [[("custom_element_id", 4)]], {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 1),
                                ("column_breakpoint", 2),
                                ("content", 3),
                                ("settings", 5),
                            ]
                        ],
                        {},
                    ),
                    7: ("wagtail.blocks.StreamBlock", [[("column", 6)]], {}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("spacing", 0), ("columns", 7), ("settings", 5)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Headline", "max_length": 200, "required": False},
                    ),
                    10: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "required": False},
                    ),
                    11: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page link", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave empty for document/page links to use their title.",
                            "label": "Title",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Open in new page", "required": False},
                    ),
                    14: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "Document link", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Download document", "required": False},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "External URL", "max_length": 255, "required": False},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page_link", 11),
                                ("title", 12),
                                ("open_in_new_page_flag", 13),
                                ("document_link", 14),
                                ("document_download_flag", 15),
                                ("external_link_url", 16),
                            ]
                        ],
                        {"label": "Link", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default theme"),
                                ("green", "Green theme"),
                            ],
                            "label": "Tile theme",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 9), ("body", 10), ("link", 17), ("theme", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Bootstrap-icon name",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("icon_name", 20), ("settings", 5)]],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 21), ("headline", 9), ("body", 10)]],
                        {},
                    ),
                    23: ("home.blocks.html.RichTextBlock", (), {}),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading text", "required": True},
                    ),
                    25: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select header level"),
                                ("h1", "H1"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 24), ("level", 25), ("settings", 5)]],
                        {},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page_link", 11),
                                ("title", 12),
                                ("open_in_new_page_flag", 13),
                                ("document_link", 14),
                                ("document_download_flag", 15),
                                ("external_link_url", 16),
                            ]
                        ],
                        {},
                    ),
                    28: ("wagtail.blocks.StructBlock", [[("settings", 5)]], {}),
                    29: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.Carousel",),
                        {},
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Static overlay text for all slides",
                            "label": "Overlay text",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("carousel", 29), ("text", 30), ("settings", 5)]],
                        {},
                    ),
                    32: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("row", 8),
                                ("tile", 19),
                                ("card", 22),
                                ("text", 23),
                                ("heading", 26),
                                ("link", 27),
                                ("flyer_swiper", 28),
                                ("carousel", 31),
                            ]
                        ],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 1),
                                ("column_breakpoint", 2),
                                ("content", 32),
                                ("settings", 5),
                            ]
                        ],
                        {},
                    ),
                    34: ("wagtail.blocks.StreamBlock", [[("column", 33)]], {}),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("spacing", 0), ("columns", 34), ("settings", 5)]],
                        {},
                    ),
                    36: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hero background will be blurred by default",
                            "label": "Background image",
                            "required": False,
                        },
                    ),
                    37: ("wagtail.blocks.StreamBlock", [[("row", 35)]], {}),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [[("background_image", 36), ("content", 37), ("settings", 5)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
