# Generated by Django 5.2.5 on 2025-09-03 11:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0096_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footer",
            name="extra_slot",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("heading", 5),
                    ("link", 12),
                    ("row", 20),
                    ("flyer_swiper", 21),
                    ("carousel", 24),
                ],
                blank=True,
                block_lookup={
                    0: ("home.blocks.html.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading text", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select header level"),
                                ("h1", "H1"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Custom element id", "required": False},
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("custom_element_id", 3)]], {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("level", 2), ("settings", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page link", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave empty for document/page links to use their title.",
                            "label": "Title",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Open in new page", "required": False},
                    ),
                    9: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "Document link", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Download document", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "External URL", "max_length": 255, "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page_link", 6),
                                ("title", 7),
                                ("open_in_new_page_flag", 8),
                                ("document_link", 9),
                                ("document_download_flag", 10),
                                ("external_link_url", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                            "help_text": "Gap between columns",
                            "label": "Spacing",
                        },
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Automatic size"),
                                ("12", "Full row"),
                                ("6", "Half - 1/2 column"),
                                ("4", "Thirds - 1/3 column"),
                                ("8", "Thirds - 2/3 column"),
                                ("3", "Quarters - 1/4 column"),
                                ("9", "Quarters - 3/4 column"),
                                ("2", "Sixths - 1/6 column"),
                                ("10", "Sixths - 5/6 column"),
                                ("1", "Twelfths - 1/12 column"),
                                ("5", "Twelfths - 5/12 column"),
                                ("7", "Twelfths - 7/12 column"),
                                ("11", "Twelfths - 11/12 column"),
                            ],
                            "label": "Column size",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Always expanded"),
                                (
                                    "sm",
                                    "sm - Expand on small screens (phone, 576px) and larger",
                                ),
                                (
                                    "md",
                                    "md - Expand on medium screens (tablet, 768px) and larger",
                                ),
                                (
                                    "lg",
                                    "lg - Expand on large screens (laptop, 992px) and larger",
                                ),
                                (
                                    "xl",
                                    "xl - Expand on extra large screens (wide monitor, 1200px)",
                                ),
                            ],
                            "label": "Column breakpoint",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("transparent", "Transparent (no colors)"),
                                ("white", "Black text on white"),
                            ],
                            "label": "Theme",
                        },
                    ),
                    17: ("wagtail.blocks.StreamBlock", [[]], {}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 14),
                                ("column_breakpoint", 15),
                                ("theme", 16),
                                ("content", 17),
                                ("settings", 4),
                            ]
                        ],
                        {},
                    ),
                    19: ("wagtail.blocks.StreamBlock", [[("column", 18)]], {}),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("spacing", 13), ("columns", 19), ("settings", 4)]],
                        {},
                    ),
                    21: ("wagtail.blocks.StructBlock", [[("settings", 4)]], {}),
                    22: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.Carousel",),
                        {},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Static overlay text for all slides",
                            "label": "Overlay text",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("carousel", 22), ("text", 23), ("settings", 4)]],
                        {},
                    ),
                },
                null=True,
                verbose_name="Extra footer slot",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("row", 36), ("hero", 39)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                            "help_text": "Gap between columns",
                            "label": "Spacing",
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Automatic size"),
                                ("12", "Full row"),
                                ("6", "Half - 1/2 column"),
                                ("4", "Thirds - 1/3 column"),
                                ("8", "Thirds - 2/3 column"),
                                ("3", "Quarters - 1/4 column"),
                                ("9", "Quarters - 3/4 column"),
                                ("2", "Sixths - 1/6 column"),
                                ("10", "Sixths - 5/6 column"),
                                ("1", "Twelfths - 1/12 column"),
                                ("5", "Twelfths - 5/12 column"),
                                ("7", "Twelfths - 7/12 column"),
                                ("11", "Twelfths - 11/12 column"),
                            ],
                            "label": "Column size",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Always expanded"),
                                (
                                    "sm",
                                    "sm - Expand on small screens (phone, 576px) and larger",
                                ),
                                (
                                    "md",
                                    "md - Expand on medium screens (tablet, 768px) and larger",
                                ),
                                (
                                    "lg",
                                    "lg - Expand on large screens (laptop, 992px) and larger",
                                ),
                                (
                                    "xl",
                                    "xl - Expand on extra large screens (wide monitor, 1200px)",
                                ),
                            ],
                            "label": "Column breakpoint",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("transparent", "Transparent (no colors)"),
                                ("white", "Black text on white"),
                            ],
                            "label": "Theme",
                        },
                    ),
                    4: ("wagtail.blocks.StreamBlock", [[]], {}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Custom element id", "required": False},
                    ),
                    6: ("wagtail.blocks.StructBlock", [[("custom_element_id", 5)]], {}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 1),
                                ("column_breakpoint", 2),
                                ("theme", 3),
                                ("content", 4),
                                ("settings", 6),
                            ]
                        ],
                        {},
                    ),
                    8: ("wagtail.blocks.StreamBlock", [[("column", 7)]], {}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("spacing", 0), ("columns", 8), ("settings", 6)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Headline", "max_length": 200, "required": False},
                    ),
                    11: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "required": False},
                    ),
                    12: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page link", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave empty for document/page links to use their title.",
                            "label": "Title",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Open in new page", "required": False},
                    ),
                    15: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "Document link", "required": False},
                    ),
                    16: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Download document", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "External URL", "max_length": 255, "required": False},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page_link", 12),
                                ("title", 13),
                                ("open_in_new_page_flag", 14),
                                ("document_link", 15),
                                ("document_download_flag", 16),
                                ("external_link_url", 17),
                            ]
                        ],
                        {"label": "Link", "required": False},
                    ),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default theme"),
                                ("green", "Green theme"),
                            ],
                            "label": "Tile theme",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 10), ("body", 11), ("link", 18), ("theme", 19)]],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Bootstrap-icon name",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("icon_name", 21), ("settings", 6)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 22), ("headline", 10), ("body", 11)]],
                        {},
                    ),
                    24: ("home.blocks.html.RichTextBlock", (), {}),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading text", "required": True},
                    ),
                    26: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select header level"),
                                ("h1", "H1"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                        },
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 25), ("level", 26), ("settings", 6)]],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page_link", 12),
                                ("title", 13),
                                ("open_in_new_page_flag", 14),
                                ("document_link", 15),
                                ("document_download_flag", 16),
                                ("external_link_url", 17),
                            ]
                        ],
                        {},
                    ),
                    29: ("wagtail.blocks.StructBlock", [[("settings", 6)]], {}),
                    30: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.Carousel",),
                        {},
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Static overlay text for all slides",
                            "label": "Overlay text",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("carousel", 30), ("text", 31), ("settings", 6)]],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("row", 9),
                                ("tile", 20),
                                ("card", 23),
                                ("text", 24),
                                ("heading", 27),
                                ("link", 28),
                                ("flyer_swiper", 29),
                                ("carousel", 32),
                            ]
                        ],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 1),
                                ("column_breakpoint", 2),
                                ("theme", 3),
                                ("content", 33),
                                ("settings", 6),
                            ]
                        ],
                        {},
                    ),
                    35: ("wagtail.blocks.StreamBlock", [[("column", 34)]], {}),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("spacing", 0), ("columns", 35), ("settings", 6)]],
                        {},
                    ),
                    37: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hero background will be blurred by default",
                            "label": "Background image",
                            "required": False,
                        },
                    ),
                    38: ("wagtail.blocks.StreamBlock", [[("row", 36)]], {}),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("background_image", 37), ("content", 38), ("settings", 6)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("heading", 5),
                    ("link", 12),
                    ("row", 20),
                    ("flyer_swiper", 21),
                    ("carousel", 24),
                ],
                blank=True,
                block_lookup={
                    0: ("home.blocks.html.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading text", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select header level"),
                                ("h1", "H1"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Custom element id", "required": False},
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("custom_element_id", 3)]], {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("level", 2), ("settings", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page link", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave empty for document/page links to use their title.",
                            "label": "Title",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Open in new page", "required": False},
                    ),
                    9: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "Document link", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Download document", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "External URL", "max_length": 255, "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page_link", 6),
                                ("title", 7),
                                ("open_in_new_page_flag", 8),
                                ("document_link", 9),
                                ("document_download_flag", 10),
                                ("external_link_url", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                            "help_text": "Gap between columns",
                            "label": "Spacing",
                        },
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Automatic size"),
                                ("12", "Full row"),
                                ("6", "Half - 1/2 column"),
                                ("4", "Thirds - 1/3 column"),
                                ("8", "Thirds - 2/3 column"),
                                ("3", "Quarters - 1/4 column"),
                                ("9", "Quarters - 3/4 column"),
                                ("2", "Sixths - 1/6 column"),
                                ("10", "Sixths - 5/6 column"),
                                ("1", "Twelfths - 1/12 column"),
                                ("5", "Twelfths - 5/12 column"),
                                ("7", "Twelfths - 7/12 column"),
                                ("11", "Twelfths - 11/12 column"),
                            ],
                            "label": "Column size",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Always expanded"),
                                (
                                    "sm",
                                    "sm - Expand on small screens (phone, 576px) and larger",
                                ),
                                (
                                    "md",
                                    "md - Expand on medium screens (tablet, 768px) and larger",
                                ),
                                (
                                    "lg",
                                    "lg - Expand on large screens (laptop, 992px) and larger",
                                ),
                                (
                                    "xl",
                                    "xl - Expand on extra large screens (wide monitor, 1200px)",
                                ),
                            ],
                            "label": "Column breakpoint",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("transparent", "Transparent (no colors)"),
                                ("white", "Black text on white"),
                            ],
                            "label": "Theme",
                        },
                    ),
                    17: ("wagtail.blocks.StreamBlock", [[]], {}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 14),
                                ("column_breakpoint", 15),
                                ("theme", 16),
                                ("content", 17),
                                ("settings", 4),
                            ]
                        ],
                        {},
                    ),
                    19: ("wagtail.blocks.StreamBlock", [[("column", 18)]], {}),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("spacing", 13), ("columns", 19), ("settings", 4)]],
                        {},
                    ),
                    21: ("wagtail.blocks.StructBlock", [[("settings", 4)]], {}),
                    22: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.Carousel",),
                        {},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Static overlay text for all slides",
                            "label": "Overlay text",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("carousel", 22), ("text", 23), ("settings", 4)]],
                        {},
                    ),
                },
                verbose_name="Page body",
            ),
        ),
    ]
