# Generated by Django 5.2.5 on 2025-09-04 10:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0101_alter_footer_extra_slot_alter_homepage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carouselslide",
            name="content",
            field=wagtail.fields.StreamField(
                [("text", 0), ("heading", 6)],
                blank=True,
                block_lookup={
                    0: ("home.blocks.html.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading text", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select header level"),
                                ("h1", "H1"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                        },
                    ),
                    3: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "label": "Rainbow effect"},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Custom element id", "required": False},
                    ),
                    5: ("wagtail.blocks.StructBlock", [[("custom_element_id", 4)]], {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 1),
                                ("level", 2),
                                ("rainbow_effect", 3),
                                ("settings", 5),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="footer",
            name="extra_slot",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("heading", 6),
                    ("link", 15),
                    ("row", 24),
                    ("flyer_swiper", 25),
                    ("carousel", 28),
                ],
                blank=True,
                block_lookup={
                    0: ("home.blocks.html.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading text", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select header level"),
                                ("h1", "H1"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                        },
                    ),
                    3: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "label": "Rainbow effect"},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Custom element id", "required": False},
                    ),
                    5: ("wagtail.blocks.StructBlock", [[("custom_element_id", 4)]], {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 1),
                                ("level", 2),
                                ("rainbow_effect", 3),
                                ("settings", 5),
                            ]
                        ],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page link", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave empty for document/page links to use their title.",
                            "label": "Title",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Open in new page", "required": False},
                    ),
                    10: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "Document link", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Download document", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "External URL", "max_length": 255, "required": False},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("default-inverse", "Inverted default"),
                                ("green", "Green"),
                                ("purple", "Purple"),
                            ],
                            "label": "Theme",
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Insert a boostrap icon name here. Look up: <a href="https://icons.getbootstrap.com/" target="_blank">here</a>',
                            "label": "Bootstrap-icon name",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page_link", 7),
                                ("title", 8),
                                ("open_in_new_page_flag", 9),
                                ("document_link", 10),
                                ("document_download_flag", 11),
                                ("external_link_url", 12),
                                ("theme", 13),
                                ("icon_name", 14),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                            "help_text": "Gap between columns",
                            "label": "Spacing",
                        },
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Automatic size"),
                                ("12", "Full row"),
                                ("6", "Half - 1/2 column"),
                                ("4", "Thirds - 1/3 column"),
                                ("8", "Thirds - 2/3 column"),
                                ("3", "Quarters - 1/4 column"),
                                ("9", "Quarters - 3/4 column"),
                                ("2", "Sixths - 1/6 column"),
                                ("10", "Sixths - 5/6 column"),
                                ("1", "Twelfths - 1/12 column"),
                                ("5", "Twelfths - 5/12 column"),
                                ("7", "Twelfths - 7/12 column"),
                                ("11", "Twelfths - 11/12 column"),
                            ],
                            "label": "Column size",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Always expanded"),
                                (
                                    "sm",
                                    "sm - Expand on small screens (phone, 576px) and larger",
                                ),
                                (
                                    "md",
                                    "md - Expand on medium screens (tablet, 768px) and larger",
                                ),
                                (
                                    "lg",
                                    "lg - Expand on large screens (laptop, 992px) and larger",
                                ),
                                (
                                    "xl",
                                    "xl - Expand on extra large screens (wide monitor, 1200px)",
                                ),
                            ],
                            "label": "Column breakpoint",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("transparent", "Transparent (no colors)"),
                                ("white", "Black text on white"),
                            ],
                            "label": "Theme",
                        },
                    ),
                    20: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "label": "Rounded borders",
                            "required": False,
                        },
                    ),
                    21: ("wagtail.blocks.StreamBlock", [[]], {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 17),
                                ("column_breakpoint", 18),
                                ("theme", 19),
                                ("round_borders", 20),
                                ("content", 21),
                                ("settings", 5),
                            ]
                        ],
                        {},
                    ),
                    23: ("wagtail.blocks.StreamBlock", [[("column", 22)]], {}),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("spacing", 16), ("columns", 23), ("settings", 5)]],
                        {},
                    ),
                    25: ("wagtail.blocks.StructBlock", [[("settings", 5)]], {}),
                    26: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.Carousel",),
                        {},
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Static overlay text for all slides",
                            "label": "Overlay text",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("carousel", 26), ("text", 27), ("settings", 5)]],
                        {},
                    ),
                },
                null=True,
                verbose_name="Extra footer slot",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("row", 40), ("hero", 43)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                            "help_text": "Gap between columns",
                            "label": "Spacing",
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Automatic size"),
                                ("12", "Full row"),
                                ("6", "Half - 1/2 column"),
                                ("4", "Thirds - 1/3 column"),
                                ("8", "Thirds - 2/3 column"),
                                ("3", "Quarters - 1/4 column"),
                                ("9", "Quarters - 3/4 column"),
                                ("2", "Sixths - 1/6 column"),
                                ("10", "Sixths - 5/6 column"),
                                ("1", "Twelfths - 1/12 column"),
                                ("5", "Twelfths - 5/12 column"),
                                ("7", "Twelfths - 7/12 column"),
                                ("11", "Twelfths - 11/12 column"),
                            ],
                            "label": "Column size",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Always expanded"),
                                (
                                    "sm",
                                    "sm - Expand on small screens (phone, 576px) and larger",
                                ),
                                (
                                    "md",
                                    "md - Expand on medium screens (tablet, 768px) and larger",
                                ),
                                (
                                    "lg",
                                    "lg - Expand on large screens (laptop, 992px) and larger",
                                ),
                                (
                                    "xl",
                                    "xl - Expand on extra large screens (wide monitor, 1200px)",
                                ),
                            ],
                            "label": "Column breakpoint",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("transparent", "Transparent (no colors)"),
                                ("white", "Black text on white"),
                            ],
                            "label": "Theme",
                        },
                    ),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "label": "Rounded borders",
                            "required": False,
                        },
                    ),
                    5: ("wagtail.blocks.StreamBlock", [[]], {}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Custom element id", "required": False},
                    ),
                    7: ("wagtail.blocks.StructBlock", [[("custom_element_id", 6)]], {}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 1),
                                ("column_breakpoint", 2),
                                ("theme", 3),
                                ("round_borders", 4),
                                ("content", 5),
                                ("settings", 7),
                            ]
                        ],
                        {},
                    ),
                    9: ("wagtail.blocks.StreamBlock", [[("column", 8)]], {}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("spacing", 0), ("columns", 9), ("settings", 7)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Headline", "max_length": 200, "required": False},
                    ),
                    12: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "required": False},
                    ),
                    13: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page link", "required": False},
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave empty for document/page links to use their title.",
                            "label": "Title",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Open in new page", "required": False},
                    ),
                    16: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "Document link", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Download document", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "External URL", "max_length": 255, "required": False},
                    ),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("default-inverse", "Inverted default"),
                                ("green", "Green"),
                                ("purple", "Purple"),
                            ],
                            "label": "Theme",
                        },
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Insert a boostrap icon name here. Look up: <a href="https://icons.getbootstrap.com/" target="_blank">here</a>',
                            "label": "Bootstrap-icon name",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page_link", 13),
                                ("title", 14),
                                ("open_in_new_page_flag", 15),
                                ("document_link", 16),
                                ("document_download_flag", 17),
                                ("external_link_url", 18),
                                ("theme", 19),
                                ("icon_name", 20),
                            ]
                        ],
                        {"label": "Link", "required": False},
                    ),
                    22: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default theme"),
                                ("green", "Green theme"),
                            ],
                            "label": "Tile theme",
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 11), ("body", 12), ("link", 21), ("theme", 22)]],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Bootstrap-icon name",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("icon_name", 24), ("settings", 7)]],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 25), ("headline", 11), ("body", 12)]],
                        {},
                    ),
                    27: ("home.blocks.html.RichTextBlock", (), {}),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading text", "required": True},
                    ),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select header level"),
                                ("h1", "H1"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                        },
                    ),
                    30: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "label": "Rainbow effect"},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 28),
                                ("level", 29),
                                ("rainbow_effect", 30),
                                ("settings", 7),
                            ]
                        ],
                        {},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page_link", 13),
                                ("title", 14),
                                ("open_in_new_page_flag", 15),
                                ("document_link", 16),
                                ("document_download_flag", 17),
                                ("external_link_url", 18),
                                ("theme", 19),
                                ("icon_name", 20),
                            ]
                        ],
                        {},
                    ),
                    33: ("wagtail.blocks.StructBlock", [[("settings", 7)]], {}),
                    34: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.Carousel",),
                        {},
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Static overlay text for all slides",
                            "label": "Overlay text",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("carousel", 34), ("text", 35), ("settings", 7)]],
                        {},
                    ),
                    37: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("row", 10),
                                ("tile", 23),
                                ("card", 26),
                                ("text", 27),
                                ("heading", 31),
                                ("link", 32),
                                ("flyer_swiper", 33),
                                ("carousel", 36),
                            ]
                        ],
                        {},
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 1),
                                ("column_breakpoint", 2),
                                ("theme", 3),
                                ("round_borders", 4),
                                ("content", 37),
                                ("settings", 7),
                            ]
                        ],
                        {},
                    ),
                    39: ("wagtail.blocks.StreamBlock", [[("column", 38)]], {}),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [[("spacing", 0), ("columns", 39), ("settings", 7)]],
                        {},
                    ),
                    41: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hero background will be blurred by default",
                            "label": "Background image",
                            "required": False,
                        },
                    ),
                    42: ("wagtail.blocks.StreamBlock", [[("row", 40)]], {}),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("background_image", 41), ("content", 42), ("settings", 7)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("heading", 6),
                    ("link", 15),
                    ("row", 24),
                    ("flyer_swiper", 25),
                    ("carousel", 28),
                ],
                blank=True,
                block_lookup={
                    0: ("home.blocks.html.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading text", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select header level"),
                                ("h1", "H1"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                        },
                    ),
                    3: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "label": "Rainbow effect"},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Custom element id", "required": False},
                    ),
                    5: ("wagtail.blocks.StructBlock", [[("custom_element_id", 4)]], {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 1),
                                ("level", 2),
                                ("rainbow_effect", 3),
                                ("settings", 5),
                            ]
                        ],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page link", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave empty for document/page links to use their title.",
                            "label": "Title",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Open in new page", "required": False},
                    ),
                    10: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "Document link", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Download document", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "External URL", "max_length": 255, "required": False},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("default-inverse", "Inverted default"),
                                ("green", "Green"),
                                ("purple", "Purple"),
                            ],
                            "label": "Theme",
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Insert a boostrap icon name here. Look up: <a href="https://icons.getbootstrap.com/" target="_blank">here</a>',
                            "label": "Bootstrap-icon name",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page_link", 7),
                                ("title", 8),
                                ("open_in_new_page_flag", 9),
                                ("document_link", 10),
                                ("document_download_flag", 11),
                                ("external_link_url", 12),
                                ("theme", 13),
                                ("icon_name", 14),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                            "help_text": "Gap between columns",
                            "label": "Spacing",
                        },
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Automatic size"),
                                ("12", "Full row"),
                                ("6", "Half - 1/2 column"),
                                ("4", "Thirds - 1/3 column"),
                                ("8", "Thirds - 2/3 column"),
                                ("3", "Quarters - 1/4 column"),
                                ("9", "Quarters - 3/4 column"),
                                ("2", "Sixths - 1/6 column"),
                                ("10", "Sixths - 5/6 column"),
                                ("1", "Twelfths - 1/12 column"),
                                ("5", "Twelfths - 5/12 column"),
                                ("7", "Twelfths - 7/12 column"),
                                ("11", "Twelfths - 11/12 column"),
                            ],
                            "label": "Column size",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Always expanded"),
                                (
                                    "sm",
                                    "sm - Expand on small screens (phone, 576px) and larger",
                                ),
                                (
                                    "md",
                                    "md - Expand on medium screens (tablet, 768px) and larger",
                                ),
                                (
                                    "lg",
                                    "lg - Expand on large screens (laptop, 992px) and larger",
                                ),
                                (
                                    "xl",
                                    "xl - Expand on extra large screens (wide monitor, 1200px)",
                                ),
                            ],
                            "label": "Column breakpoint",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("transparent", "Transparent (no colors)"),
                                ("white", "Black text on white"),
                            ],
                            "label": "Theme",
                        },
                    ),
                    20: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "label": "Rounded borders",
                            "required": False,
                        },
                    ),
                    21: ("wagtail.blocks.StreamBlock", [[]], {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 17),
                                ("column_breakpoint", 18),
                                ("theme", 19),
                                ("round_borders", 20),
                                ("content", 21),
                                ("settings", 5),
                            ]
                        ],
                        {},
                    ),
                    23: ("wagtail.blocks.StreamBlock", [[("column", 22)]], {}),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("spacing", 16), ("columns", 23), ("settings", 5)]],
                        {},
                    ),
                    25: ("wagtail.blocks.StructBlock", [[("settings", 5)]], {}),
                    26: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.Carousel",),
                        {},
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Static overlay text for all slides",
                            "label": "Overlay text",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("carousel", 26), ("text", 27), ("settings", 5)]],
                        {},
                    ),
                },
                verbose_name="Page body",
            ),
        ),
    ]
