# Generated by Django 5.2.5 on 2025-09-05 11:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0107_alter_footer_extra_slot_alter_homepage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footer",
            name="extra_slot",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("heading", 6),
                    ("link", 15),
                    ("flyer_swiper", 16),
                    ("carousel", 20),
                ],
                blank=True,
                block_lookup={
                    0: ("home.blocks.html.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading text", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select header level"),
                                ("1", "H1"),
                                ("2", "H2"),
                                ("3", "H3"),
                                ("4", "H4"),
                            ],
                        },
                    ),
                    3: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "label": "Rainbow effect",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Custom element id", "required": False},
                    ),
                    5: ("wagtail.blocks.StructBlock", [[("custom_element_id", 4)]], {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 1),
                                ("level", 2),
                                ("rainbow_effect", 3),
                                ("settings", 5),
                            ]
                        ],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page link", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave empty for document/page links to use their title.",
                            "label": "Title",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Open in new page", "required": False},
                    ),
                    10: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "Document link", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Download document", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "External URL", "max_length": 255, "required": False},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("default-inverse", "Inverted default"),
                                ("green", "Green"),
                                ("purple", "Purple"),
                            ],
                            "label": "Theme",
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Insert a boostrap icon name here. Look up: <a href="https://icons.getbootstrap.com/" target="_blank">here</a>',
                            "label": "Bootstrap-icon name",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page_link", 7),
                                ("title", 8),
                                ("open_in_new_page_flag", 9),
                                ("document_link", 10),
                                ("document_download_flag", 11),
                                ("external_link_url", 12),
                                ("theme", 13),
                                ("icon_name", 14),
                            ]
                        ],
                        {},
                    ),
                    16: ("wagtail.blocks.StructBlock", [[("settings", 5)]], {}),
                    17: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.Carousel",),
                        {},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Static overlay text for all slides",
                            "label": "Overlay text",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "label": "Show opening hours",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("carousel", 17),
                                ("text", 18),
                                ("show_opening_hours", 19),
                                ("settings", 5),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
                verbose_name="Extra footer slot",
            ),
        ),
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("heading", 6),
                    ("link", 15),
                    ("flyer_swiper", 16),
                    ("carousel", 20),
                ],
                blank=True,
                block_lookup={
                    0: ("home.blocks.html.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading text", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select header level"),
                                ("1", "H1"),
                                ("2", "H2"),
                                ("3", "H3"),
                                ("4", "H4"),
                            ],
                        },
                    ),
                    3: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "label": "Rainbow effect",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Custom element id", "required": False},
                    ),
                    5: ("wagtail.blocks.StructBlock", [[("custom_element_id", 4)]], {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 1),
                                ("level", 2),
                                ("rainbow_effect", 3),
                                ("settings", 5),
                            ]
                        ],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page link", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave empty for document/page links to use their title.",
                            "label": "Title",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Open in new page", "required": False},
                    ),
                    10: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "Document link", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Download document", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "External URL", "max_length": 255, "required": False},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("default-inverse", "Inverted default"),
                                ("green", "Green"),
                                ("purple", "Purple"),
                            ],
                            "label": "Theme",
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Insert a boostrap icon name here. Look up: <a href="https://icons.getbootstrap.com/" target="_blank">here</a>',
                            "label": "Bootstrap-icon name",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page_link", 7),
                                ("title", 8),
                                ("open_in_new_page_flag", 9),
                                ("document_link", 10),
                                ("document_download_flag", 11),
                                ("external_link_url", 12),
                                ("theme", 13),
                                ("icon_name", 14),
                            ]
                        ],
                        {},
                    ),
                    16: ("wagtail.blocks.StructBlock", [[("settings", 5)]], {}),
                    17: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.Carousel",),
                        {},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Static overlay text for all slides",
                            "label": "Overlay text",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "label": "Show opening hours",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("carousel", 17),
                                ("text", 18),
                                ("show_opening_hours", 19),
                                ("settings", 5),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Page body",
            ),
        ),
    ]
