# Generated by Django 5.2.5 on 2025-09-05 11:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0108_alter_footer_extra_slot_alter_standardpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("row", 44), ("hero", 47)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                            "help_text": "Gap between columns",
                            "label": "Spacing",
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 200, "required": False},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Subtitle", "max_length": 200, "required": False},
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Automatic size"),
                                ("12", "Full row"),
                                ("6", "Half - 1/2 column"),
                                ("4", "Thirds - 1/3 column"),
                                ("8", "Thirds - 2/3 column"),
                                ("3", "Quarters - 1/4 column"),
                                ("9", "Quarters - 3/4 column"),
                                ("2", "Sixths - 1/6 column"),
                                ("10", "Sixths - 5/6 column"),
                                ("1", "Twelfths - 1/12 column"),
                                ("5", "Twelfths - 5/12 column"),
                                ("7", "Twelfths - 7/12 column"),
                                ("11", "Twelfths - 11/12 column"),
                            ],
                            "label": "Column size",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Always expanded"),
                                (
                                    "sm",
                                    "sm - Expand on small screens (phone, 576px) and larger",
                                ),
                                (
                                    "md",
                                    "md - Expand on medium screens (tablet, 768px) and larger",
                                ),
                                (
                                    "lg",
                                    "lg - Expand on large screens (laptop, 992px) and larger",
                                ),
                                (
                                    "xl",
                                    "xl - Expand on extra large screens (wide monitor, 1200px)",
                                ),
                            ],
                            "label": "Column breakpoint",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("transparent", "Transparent (no colors)"),
                                ("white", "Black text on white"),
                            ],
                            "label": "Theme",
                        },
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "label": "Rounded borders",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Sticker", "required": False},
                    ),
                    8: ("wagtail.blocks.StreamBlock", [[]], {}),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Custom element id", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("custom_element_id", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 3),
                                ("column_breakpoint", 4),
                                ("theme", 5),
                                ("round_borders", 6),
                                ("sticker_image", 7),
                                ("content", 8),
                                ("settings", 10),
                            ]
                        ],
                        {},
                    ),
                    12: ("wagtail.blocks.StreamBlock", [[("column", 11)]], {}),
                    13: ("wagtail.blocks.StructBlock", [[("columns", 12)]], {}),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Headline", "max_length": 200, "required": False},
                    ),
                    15: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "required": False},
                    ),
                    16: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page link", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave empty for document/page links to use their title.",
                            "label": "Title",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Open in new page", "required": False},
                    ),
                    19: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "Document link", "required": False},
                    ),
                    20: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Download document", "required": False},
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "External URL", "max_length": 255, "required": False},
                    ),
                    22: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("default-inverse", "Inverted default"),
                                ("green", "Green"),
                                ("purple", "Purple"),
                            ],
                            "label": "Theme",
                        },
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Insert a boostrap icon name here. Look up: <a href="https://icons.getbootstrap.com/" target="_blank">here</a>',
                            "label": "Bootstrap-icon name",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page_link", 16),
                                ("title", 17),
                                ("open_in_new_page_flag", 18),
                                ("document_link", 19),
                                ("document_download_flag", 20),
                                ("external_link_url", 21),
                                ("theme", 22),
                                ("icon_name", 23),
                            ]
                        ],
                        {"label": "Link", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default theme"),
                                ("green", "Green theme"),
                            ],
                            "label": "Tile theme",
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 14), ("body", 15), ("link", 24), ("theme", 25)]],
                        {},
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Bootstrap-icon name",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("icon_name", 27), ("settings", 10)]],
                        {},
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 28), ("headline", 14), ("body", 15)]],
                        {},
                    ),
                    30: ("home.blocks.html.RichTextBlock", (), {}),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading text", "required": True},
                    ),
                    32: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select header level"),
                                ("1", "H1"),
                                ("2", "H2"),
                                ("3", "H3"),
                                ("4", "H4"),
                            ],
                        },
                    ),
                    33: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "label": "Rainbow effect",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 31),
                                ("level", 32),
                                ("rainbow_effect", 33),
                                ("settings", 10),
                            ]
                        ],
                        {},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page_link", 16),
                                ("title", 17),
                                ("open_in_new_page_flag", 18),
                                ("document_link", 19),
                                ("document_download_flag", 20),
                                ("external_link_url", 21),
                                ("theme", 22),
                                ("icon_name", 23),
                            ]
                        ],
                        {},
                    ),
                    36: ("wagtail.blocks.StructBlock", [[("settings", 10)]], {}),
                    37: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.Carousel",),
                        {},
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Static overlay text for all slides",
                            "label": "Overlay text",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "label": "Show opening hours",
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("carousel", 37),
                                ("text", 38),
                                ("show_opening_hours", 39),
                                ("settings", 10),
                            ]
                        ],
                        {},
                    ),
                    41: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("row", 13),
                                ("tile", 26),
                                ("card", 29),
                                ("text", 30),
                                ("heading", 34),
                                ("link", 35),
                                ("flyer_swiper", 36),
                                ("carousel", 40),
                            ]
                        ],
                        {},
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("column_size", 3),
                                ("column_breakpoint", 4),
                                ("theme", 5),
                                ("round_borders", 6),
                                ("sticker_image", 7),
                                ("content", 41),
                                ("settings", 10),
                            ]
                        ],
                        {},
                    ),
                    43: ("wagtail.blocks.StreamBlock", [[("column", 42)]], {}),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("spacing", 0),
                                ("title_text", 1),
                                ("subtitle_text", 2),
                                ("columns", 43),
                                ("settings", 10),
                            ]
                        ],
                        {},
                    ),
                    45: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Hero background will be blurred by default",
                            "label": "Background image",
                            "required": False,
                        },
                    ),
                    46: ("wagtail.blocks.StreamBlock", [[("row", 44)]], {}),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("background_image", 45), ("content", 46), ("settings", 10)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
