# Generated by Django 5.2.5 on 2025-11-26 11:50

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0116_alter_footer_extra_slot_alter_homepage_body_and_more"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenancePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("row", 43), ("hero", 50), ("flyer_swiper", 51)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("1", "1"),
                                        ("2", "2"),
                                        ("3", "3"),
                                        ("4", "4"),
                                    ],
                                    "help_text": "Gap between columns",
                                    "label": "Spacing",
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Title",
                                    "max_length": 200,
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Subtitle",
                                    "max_length": 200,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("", "Automatic size"),
                                        ("12", "Full row"),
                                        ("6", "Half - 1/2 column"),
                                        ("4", "Thirds - 1/3 column"),
                                        ("8", "Thirds - 2/3 column"),
                                        ("3", "Quarters - 1/4 column"),
                                        ("9", "Quarters - 3/4 column"),
                                        ("2", "Sixths - 1/6 column"),
                                        ("10", "Sixths - 5/6 column"),
                                        ("1", "Twelfths - 1/12 column"),
                                        ("5", "Twelfths - 5/12 column"),
                                        ("7", "Twelfths - 7/12 column"),
                                        ("11", "Twelfths - 11/12 column"),
                                    ],
                                    "label": "Column size",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("", "Always expanded"),
                                        (
                                            "sm",
                                            "sm - Expand on small screens (phone, 576px) and larger",
                                        ),
                                        (
                                            "md",
                                            "md - Expand on medium screens (tablet, 768px) and larger",
                                        ),
                                        (
                                            "lg",
                                            "lg - Expand on large screens (laptop, 992px) and larger",
                                        ),
                                        (
                                            "xl",
                                            "xl - Expand on extra large screens (wide monitor, 1200px)",
                                        ),
                                    ],
                                    "label": "Column breakpoint",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("transparent", "Transparent (no colors)"),
                                        ("white", "Black text on white"),
                                    ],
                                    "label": "Theme",
                                },
                            ),
                            6: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "label": "Rounded borders",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Sticker", "required": False},
                            ),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Headline",
                                    "max_length": 200,
                                    "required": False,
                                },
                            ),
                            9: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic"], "required": False},
                            ),
                            10: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page link", "required": False},
                            ),
                            11: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave empty for document/page links to use their title.",
                                    "label": "Title",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            12: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"label": "Open in new page", "required": False},
                            ),
                            13: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"label": "Document link", "required": False},
                            ),
                            14: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"label": "Download document", "required": False},
                            ),
                            15: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "External URL",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            16: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("default", "Default"),
                                        ("default-inverse", "Inverted default"),
                                        ("green", "Green"),
                                        ("purple", "Purple"),
                                    ],
                                    "label": "Theme",
                                },
                            ),
                            17: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": 'Insert a boostrap icon name here. Look up: <a href="https://icons.getbootstrap.com/" target="_blank">here</a>',
                                    "label": "Bootstrap-icon name",
                                    "max_length": 100,
                                    "required": False,
                                },
                            ),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("page_link", 10),
                                        ("title", 11),
                                        ("open_in_new_page_flag", 12),
                                        ("document_link", 13),
                                        ("document_download_flag", 14),
                                        ("external_link_url", 15),
                                        ("theme", 16),
                                        ("icon_name", 17),
                                    ]
                                ],
                                {"label": "Link", "required": False},
                            ),
                            19: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("default", "Default theme"),
                                        ("green", "Green theme"),
                                    ],
                                    "label": "Tile theme",
                                    "required": False,
                                },
                            ),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("headline", 8),
                                        ("body", 9),
                                        ("link", 18),
                                        ("theme", 19),
                                    ]
                                ],
                                {},
                            ),
                            21: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Bootstrap-icon name",
                                    "max_length": 100,
                                    "required": False,
                                },
                            ),
                            22: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Custom element id", "required": False},
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [[("custom_element_id", 22)]],
                                {},
                            ),
                            24: (
                                "wagtail.blocks.StructBlock",
                                [[("icon_name", 21), ("settings", 23)]],
                                {},
                            ),
                            25: (
                                "wagtail.blocks.StructBlock",
                                [[("icon", 24), ("headline", 8), ("body", 9)]],
                                {},
                            ),
                            26: ("home.blocks.html.RichTextBlock", (), {}),
                            27: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Heading text", "required": True},
                            ),
                            28: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "blank": True,
                                    "choices": [
                                        ("", "Select header level"),
                                        ("1", "H1"),
                                        ("2", "H2"),
                                        ("3", "H3"),
                                        ("4", "H4"),
                                    ],
                                },
                            ),
                            29: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "label": "Rainbow effect",
                                    "required": False,
                                },
                            ),
                            30: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("text", 27),
                                        ("level", 28),
                                        ("rainbow_effect", 29),
                                        ("settings", 23),
                                    ]
                                ],
                                {},
                            ),
                            31: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("page_link", 10),
                                        ("title", 11),
                                        ("open_in_new_page_flag", 12),
                                        ("document_link", 13),
                                        ("document_download_flag", 14),
                                        ("external_link_url", 15),
                                        ("theme", 16),
                                        ("icon_name", 17),
                                    ]
                                ],
                                {},
                            ),
                            32: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                ("home.Carousel",),
                                {},
                            ),
                            33: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Static overlay text for all slides",
                                    "label": "Overlay text",
                                    "max_length": 500,
                                    "required": False,
                                },
                            ),
                            34: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "label": "Show opening hours",
                                    "required": False,
                                },
                            ),
                            35: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("carousel", 32),
                                        ("text", 33),
                                        ("show_opening_hours", 34),
                                        ("settings", 23),
                                    ]
                                ],
                                {},
                            ),
                            36: (
                                "wagtail.blocks.StreamBlock",
                                [[("tile", 20), ("card", 25)]],
                                {},
                            ),
                            37: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("column_size", 3),
                                        ("column_breakpoint", 4),
                                        ("theme", 5),
                                        ("round_borders", 6),
                                        ("sticker_image", 7),
                                        ("content", 36),
                                        ("settings", 23),
                                    ]
                                ],
                                {},
                            ),
                            38: ("wagtail.blocks.StreamBlock", [[("column", 37)]], {}),
                            39: ("wagtail.blocks.StructBlock", [[("columns", 38)]], {}),
                            40: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("tile", 20),
                                        ("card", 25),
                                        ("text", 26),
                                        ("heading", 30),
                                        ("link", 31),
                                        ("carousel", 35),
                                        ("row", 39),
                                    ]
                                ],
                                {},
                            ),
                            41: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("column_size", 3),
                                        ("column_breakpoint", 4),
                                        ("theme", 5),
                                        ("round_borders", 6),
                                        ("sticker_image", 7),
                                        ("content", 40),
                                        ("settings", 23),
                                    ]
                                ],
                                {},
                            ),
                            42: ("wagtail.blocks.StreamBlock", [[("column", 41)]], {}),
                            43: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("spacing", 0),
                                        ("title_text", 1),
                                        ("subtitle_text", 2),
                                        ("columns", 42),
                                        ("settings", 23),
                                    ]
                                ],
                                {},
                            ),
                            44: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Hero background will be blurred by default",
                                    "label": "Background image",
                                    "required": False,
                                },
                            ),
                            45: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("tile", 20),
                                        ("card", 25),
                                        ("text", 26),
                                        ("heading", 30),
                                        ("link", 31),
                                        ("carousel", 35),
                                    ]
                                ],
                                {},
                            ),
                            46: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("column_size", 3),
                                        ("column_breakpoint", 4),
                                        ("theme", 5),
                                        ("round_borders", 6),
                                        ("sticker_image", 7),
                                        ("content", 45),
                                        ("settings", 23),
                                    ]
                                ],
                                {},
                            ),
                            47: ("wagtail.blocks.StreamBlock", [[("column", 46)]], {}),
                            48: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("spacing", 0),
                                        ("title_text", 1),
                                        ("subtitle_text", 2),
                                        ("columns", 47),
                                        ("settings", 23),
                                    ]
                                ],
                                {},
                            ),
                            49: ("wagtail.blocks.StreamBlock", [[("row", 48)]], {}),
                            50: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("background_image", 44),
                                        ("content", 49),
                                        ("settings", 23),
                                    ]
                                ],
                                {},
                            ),
                            51: (
                                "wagtail.blocks.StructBlock",
                                [[("settings", 23)]],
                                {},
                            ),
                        },
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
