# Generated by Django 5.2.5 on 2025-11-26 12:09

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0117_maintenancepage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maintenancepage",
            options={"verbose_name": "Maintenance page"},
        ),
        migrations.RemoveField(
            model_name="maintenancepage",
            name="body",
        ),
        migrations.AddField(
            model_name="maintenancepage",
            name="headline",
            field=models.CharField(
                blank=True, help_text="Headline text", verbose_name="Headline"
            ),
        ),
        migrations.AddField(
            model_name="maintenancepage",
            name="message",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Short message to the user",
                verbose_name="Message text",
            ),
        ),
        migrations.AddField(
            model_name="maintenancepage",
            name="sub_headline",
            field=models.CharField(
                blank=True, help_text="Subtitle", verbose_name="Sub headline"
            ),
        ),
    ]
